import Head from 'next/head'
import Image from 'next/image'
import Popular from '../components/Popular'
import Veggie from '../components/Veggie'
import Header from '../components/Header'
import Footer from '../components/Footer'

import SearchResults from '../components/SearchResults'


export default function Home({ popular, veggie }) {
  
  return (
    <div>
      <Head>
        <title>FudTruck</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

     
      <Header />

      <SearchResults />
      <Popular popular={popular} />
      <Veggie veggie={veggie} />
      <Footer />


    </div>
  )
}

export async function getStaticProps() {

  const apiPopular = await fetch(`https://api.spoonacular.com/recipes/random?apiKey=${process.env.NEXT_PUBLIC_API_KEY}&number=9`)
  const apiVeggie = await fetch(`https://api.spoonacular.com/recipes/random?apiKey=${process.env.NEXT_PUBLIC_API_KEY}&number=12&tags=vegetarian`)

  const popular = await apiPopular.json();
  const veggie = await apiVeggie.json();
  

  return {
    props: {
      popular: popular,
      veggie: veggie
    }
    
  }
}
